(function () {
  'use strict';
  // Serialized into standalone games. No editor globals or server calls belong here.
  window.InkySlot.runGame = function runGame(project, toyArt, toyNames, fonts, themes) {
    'use strict';
    const s=project.settings, root=document.getElementById('slot-game');
    const palette=themes[s.theme];for(const [i,name] of ['machine','panel','accent'].entries())root.style.setProperty('--'+name,palette[i+1]);
    const labels={
      en:{coin:'Insert coin',grab:'GRAB',left:'Move left',right:'Move right',collection:'Your toys',ready:'Insert a coin to activate the claw.',move:'Choose a column, then press GRAB.',grabbing:'Catching a toy…',answer:'Answer the question to win this toy.',empty:'This column is empty. Choose another column.',choose:'Choose another',correct:'Correct! Click your toy in the tray to collect it.',wrong:'Not quite. The toy goes back; the next attempt has a new question.',timeout:'Time’s up. The toy goes back.',collect:'Click the toy in the tray to collect it.',finish:'Game complete!',again:'Play again',reset:'Reset game',sound:'Sound',check:'Check answer',placeholder:'Your answer…',scratch:'Scratch paper',clear:'Clear',eraser:'Eraser',close:'Close paper',rightCount:'Correct',wrongCount:'Wrong',attempt:'Attempt',of:'of',tray:'PRIZE TRAY',collected:'Toys collected'},
      ru:{coin:'Монетка',grab:'ПОЙМАТЬ',left:'Влево',right:'Вправо',collection:'Игрушки',ready:'Вставьте монетку.',move:'Выберите ряд и поймайте игрушку.',grabbing:'Ловим игрушку…',answer:'Ответьте на вопрос.',empty:'Этот ряд пуст. Выберите другой.',choose:'Выбрать другой',correct:'Верно! Заберите игрушку из лотка.',wrong:'Неверно. Игрушка вернётся, дальше новый вопрос.',timeout:'Время вышло. Игрушка вернётся.',collect:'Нажмите на игрушку в лотке.',finish:'Игра окончена!',again:'Сыграть ещё раз',reset:'Заново',sound:'Звук',check:'Проверить',placeholder:'Ваш ответ…',scratch:'Черновик',clear:'Очистить',eraser:'Ластик',close:'Закрыть',rightCount:'Верно',wrongCount:'Ошибок',attempt:'Попытка',of:'из',tray:'ЛОТОК',collected:'Собрано игрушек'},
      de:{coin:'Münze',grab:'GREIFEN',left:'Links',right:'Rechts',collection:'Spielzeuge',ready:'Wirf eine Münze ein.',move:'Wähle eine Spalte und greife zu.',grabbing:'Spielzeug greifen…',answer:'Beantworte die Frage.',empty:'Diese Spalte ist leer.',choose:'Andere wählen',correct:'Richtig! Hole dein Spielzeug aus dem Fach.',wrong:'Falsch. Das Spielzeug fällt zurück. Nächste Frage!',timeout:'Zeit abgelaufen.',collect:'Klicke auf das Spielzeug im Fach.',finish:'Spiel beendet!',again:'Noch einmal',reset:'Neustart',sound:'Ton',check:'Prüfen',placeholder:'Deine Antwort…',scratch:'Notizblatt',clear:'Leeren',eraser:'Radierer',close:'Schließen',rightCount:'Richtig',wrongCount:'Falsch',attempt:'Versuch',of:'von',tray:'AUSGABE',collected:'Gesammelte Spielzeuge'},
      zh:{coin:'投币',grab:'抓取',left:'向左',right:'向右',collection:'玩具',ready:'投币开始。',move:'选择一列，然后抓取。',grabbing:'抓取玩具…',answer:'回答问题。',empty:'这一列是空的。',choose:'选择另一列',correct:'答对了！点击出口的玩具。',wrong:'答错了。玩具掉回去，下一题！',timeout:'时间到。',collect:'点击出口的玩具来收集。',finish:'游戏结束！',again:'再玩一次',reset:'重置',sound:'声音',check:'检查答案',placeholder:'你的答案…',scratch:'草稿',clear:'清除',eraser:'橡皮擦',close:'关闭',rightCount:'正确',wrongCount:'错误',attempt:'尝试',of:'/',tray:'出口',collected:'收集的玩具'}
    }[s.language];
    document.documentElement.lang=s.language;
    const reduced=!s.animations||matchMedia('(prefers-reduced-motion: reduce)').matches;
    root.classList.toggle('reduced',reduced);root.classList.toggle('transparent',s.transparent);
    const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
    const button=(text,cls,fn)=>{const b=make('button',cls,text);b.type='button';if(fn)b.addEventListener('click',fn);return b;};
    const img=(src,cls,alt,fallback)=>{const e=make('img',cls);e.alt=alt||'';e.src=src;e.onerror=()=>{if(fallback&&e.getAttribute('src')!==fallback)e.src=fallback;else e.hidden=true;};return e;};
    if(s.background&&!s.transparent)root.append(img(s.background,'game-background',''));
    let state='start',index=0,col=1,correct=0,wrong=0,selected=null,muted=false,deadline=0,timer=null,generation=0;
    const pending=new Set(),oscillators=new Set();let audioContext=null,questionAudio=null;
    function setState(next){state=next;root.dataset.state=next;root.dataset.attempt=String(index);}
    function later(fn,ms){const id=setTimeout(()=>{pending.delete(id);fn();},reduced?Math.min(ms,35):ms);pending.add(id);return id;}
    function clearTimer(){clearInterval(timer);timer=null;}
    function stopAudio(){if(questionAudio){questionAudio.pause();questionAudio.removeAttribute('src');questionAudio.load();questionAudio=null;}oscillators.forEach(o=>{try{o.stop();}catch(_){}});oscillators.clear();}
    function cleanup(){generation++;clearTimer();pending.forEach(clearTimeout);pending.clear();root.querySelectorAll('.confetti-piece').forEach(e=>e.remove());stopAudio();}
    function unlock(){try{audioContext=audioContext||new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});}catch(_){}}
    function sound(kind){if(!s.sounds||muted||!audioContext)return;const notes=kind==='wrong'?[260,140]:kind==='correct'?[523,659,784,1046]:[1200,800];notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),at=audioContext.currentTime+i*.1;o.type=kind==='wrong'?'triangle':'sine';o.frequency.value=freq;g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(.12,at+.01);g.gain.exponentialRampToValueAtTime(.001,at+.2);o.connect(g);g.connect(audioContext.destination);oscillators.add(o);o.onended=()=>{oscillators.delete(o);o.disconnect();g.disconnect();};o.start(at);o.stop(at+.22);});}
    const top=make('header','game-top'),title=make('span','game-title',s.title),tools=make('div','game-tools');
    const mute=button(labels.sound+' ✓','',()=>{muted=!muted;mute.textContent=labels.sound+(muted?' ×':' ✓');mute.setAttribute('aria-pressed',String(muted));if(questionAudio)questionAudio.muted=muted;if(muted)oscillators.forEach(o=>{try{o.stop();}catch(_){}});});mute.setAttribute('aria-pressed','false');
    const reset=button(labels.reset,'',()=>resetGame());reset.id='reset-game';tools.append(mute,reset);top.append(title,tools);
    const message=make('p','game-message',labels.ready);message.id='game-message';message.setAttribute('role','status');
    const layout=make('div','machine-layout'),collectionPanel=make('aside','collection-panel'),collection=make('div','collection');collection.id='collection';collectionPanel.append(make('h2','',labels.collection),collection);
    const machine=make('section','machine'),marquee=make('div','marquee','★  INKY PAWS  ★'),glass=make('div','glass');glass.id='glass';glass.append(make('div','shelf one'),make('div','shelf two'));
    const cord=make('div','claw-cord'),claw=make('div','claw');claw.id='claw';claw.setAttribute('aria-hidden','true');
    claw.innerHTML='<svg viewBox="0 0 60 60"><path d="M30 0V16" stroke="#5a706a" stroke-width="5"/><rect x="20" y="12" width="20" height="14" rx="5" fill="#819991" stroke="#344e45" stroke-width="2"/><path class="left-prong" d="M23 23 9 41 18 54" fill="none" stroke="#4b655b" stroke-width="6" stroke-linecap="round"/><path class="right-prong" d="m37 23 14 18-9 13" fill="none" stroke="#4b655b" stroke-width="6" stroke-linecap="round"/></svg>';
    const order=[0,3,5,4,2,1,8,7,6];
    const toys=order.map((id,position)=>{
      const config=project.toys[id],toy=button('','toy',()=>collectToy());toy.id='toy-'+(id+1);toy.disabled=true;toy.setAttribute('aria-label','Collect '+toyNames[id]);toy.append(img(config.src||toyArt[id],'',toyNames[id],toyArt[id]));
      const item={id,col:position%3,x:16.667+33.333*(position%3)+config.offsetX/3,y:39+22*Math.floor(position/3)+config.offsetY/4,scale:config.scale,element:toy,collected:false};glass.append(toy);return item;
    });
    glass.append(cord,claw);
    const controls=make('div','machine-controls'),left=button('←','',()=>move(-1)),grab=button(labels.grab,'grab',grabToy),right=button('→','',()=>move(1));left.id='move-left';right.id='move-right';grab.id='grab';left.setAttribute('aria-label',labels.left);right.setAttribute('aria-label',labels.right);controls.append(left,grab,right);
    const bottom=make('div','machine-bottom'),tray=make('div','tray'),coin=button('','coin-button',insertCoin);tray.id='prize-tray';coin.id='insert-coin';coin.append(make('span','','✦'),document.createTextNode(labels.coin));bottom.append(tray,coin);machine.append(marquee,glass,controls,bottom);layout.append(collectionPanel,machine);
    const attempts=make('p','attempts');attempts.id='attempts';root.append(top,message,layout,attempts);
    const screen=make('div','screen-layer');screen.id='screen';const screenCard=make('section','screen-card');screen.append(screenCard);root.append(screen);
    const taskLayer=make('div','task-layer');taskLayer.id='task-layer';taskLayer.hidden=true;const taskCard=make('section','task-card');taskCard.setAttribute('role','dialog');taskCard.setAttribute('aria-modal','true');taskCard.setAttribute('aria-labelledby','question-text');taskLayer.append(taskCard);root.append(taskLayer);
    const header=make('div','task-header'),timerBadge=make('span','timer'),scratchToggle=button(labels.scratch,'',()=>{scratch.hidden=!scratch.hidden;scratchToggle.textContent=scratch.hidden?labels.scratch:labels.close;if(!scratch.hidden)sizeCanvas();});timerBadge.id='question-timer';scratchToggle.hidden=!s.scratchpad;header.append(timerBadge,scratchToggle);
    const qtext=make('h2','question-text');qtext.id='question-text';qtext.tabIndex=-1;
    const media=make('div','task-media'),answers=make('div','answer-options'),feedback=make('p','task-feedback');answers.id='answers';feedback.id='feedback';feedback.setAttribute('role','status');
    const scratch=make('div','scratchpad');scratch.hidden=true;scratch.id='scratchpad';const scratchTools=make('div','scratch-tools'),color=make('input'),size=make('input'),canvas=make('canvas');canvas.id='scratch-canvas';canvas.setAttribute('aria-label','Drawing area for scratch work');color.type='color';color.value='#356854';color.setAttribute('aria-label','Pen color');size.type='range';size.min='1';size.max='30';size.value='4';size.setAttribute('aria-label','Pen width');let erasing=false,drawing=false,last=null;
    const eraser=button(labels.eraser,'',()=>{erasing=!erasing;eraser.setAttribute('aria-pressed',String(erasing));}),clear=button(labels.clear,'',clearCanvas);eraser.setAttribute('aria-pressed','false');scratchTools.append(color,size,eraser,clear);scratch.append(scratchTools,canvas);taskCard.append(header,qtext,media,answers,feedback,scratch);
    function clearCanvas(){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);}
    function sizeCanvas(){const rect=canvas.getBoundingClientRect();if(!rect.width)return;const previous=document.createElement('canvas');previous.width=canvas.width;previous.height=canvas.height;previous.getContext('2d').drawImage(canvas,0,0);canvas.width=Math.round(rect.width*devicePixelRatio);canvas.height=Math.round(rect.height*devicePixelRatio);canvas.getContext('2d').drawImage(previous,0,0);}
    function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
    function draw(e){if(!drawing)return;const now=point(e),ctx=canvas.getContext('2d');ctx.globalCompositeOperation=erasing?'destination-out':'source-over';ctx.lineWidth=Number(size.value)*devicePixelRatio;ctx.lineCap='round';ctx.strokeStyle=color.value;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(now.x+.01,now.y);ctx.stroke();last=now;}
    canvas.onpointerdown=e=>{drawing=true;last=point(e);canvas.setPointerCapture(e.pointerId);draw(e);};canvas.onpointermove=draw;canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;};color.oninput=()=>{erasing=false;eraser.setAttribute('aria-pressed','false');};window.addEventListener('resize',()=>{if(!scratch.hidden)sizeCanvas();});
    function restore(item){const e=item.element;glass.append(e);e.hidden=false;e.disabled=true;e.classList.remove('held');e.style.left=item.x+'%';e.style.top=item.y+'%';e.style.transform='translate(-50%,-50%) scale('+item.scale+')';}
    function positionClaw(y=6){const x=16.667+33.333*col;claw.style.left=x+'%';claw.style.top=y+'%';cord.style.left=x+'%';cord.style.height=(y+2)+'%';}
    function updateControls(){left.disabled=state!=='playing'||col===0;right.disabled=state!=='playing'||col===2;grab.disabled=state!=='playing';coin.disabled=state!=='waiting-coin';attempts.textContent=labels.attempt+' '+Math.min(index+1,9)+' '+labels.of+' 9 · '+labels.collected+': '+correct;}
    function waiting(){col=1;positionClaw();claw.classList.remove('closed');selected=null;setState('waiting-coin');message.textContent=labels.ready;updateControls();coin.focus({preventScroll:true});}
    function resetGame(){cleanup();index=0;col=1;correct=0;wrong=0;selected=null;collection.replaceChildren();for(let i=0;i<9;i++){const slot=make('div','collection-slot',String(i+1));collection.append(slot);}tray.replaceChildren(document.createTextNode(labels.tray));toys.forEach(item=>{item.collected=false;restore(item);});taskLayer.hidden=true;scratch.hidden=true;clearCanvas();claw.classList.remove('closed');positionClaw();screen.hidden=false;screenCard.replaceChildren(make('div','screen-mark','✦'),make('h1','',s.title),make('p','',s.instruction));const play=button(s.startText,'primary',()=>{unlock();screen.hidden=true;waiting();});play.id='play';screenCard.append(play);setState('start');message.textContent=labels.ready;updateControls();}
    function insertCoin(){if(state!=='waiting-coin')return;unlock();sound('coin');setState('playing');message.textContent=labels.move;updateControls();grab.focus({preventScroll:true});}
    function move(delta){if(state!=='playing')return;col=Math.max(0,Math.min(2,col+delta));positionClaw();updateControls();}
    function grabToy(){
      if(state!=='playing')return;
      const available=toys.filter(t=>t.col===col&&!t.collected);
      if(!available.length){setState('empty-column');updateControls();message.replaceChildren(document.createTextNode(labels.empty+' '));message.append(button(labels.choose,'',()=>{setState('playing');message.textContent=labels.move;updateControls();left.disabled?right.focus():left.focus();}));return;}
      selected=available[Math.floor(Math.random()*available.length)];setState('grabbing');updateControls();message.textContent=labels.grabbing;positionClaw(selected.y-13);
      later(()=>{claw.classList.add('closed');selected.element.classList.add('held');selected.element.style.left=(16.667+33.333*col)+'%';later(()=>{positionClaw();selected.element.style.top='20%';later(showTask,650);},250);},650);
    }
    function showTask(){
      setState('question');message.textContent=labels.answer;taskLayer.hidden=false;scratch.hidden=true;scratchToggle.textContent=labels.scratch;clearCanvas();answers.replaceChildren();media.replaceChildren();feedback.textContent='';const q=project.questions[index];qtext.textContent=q.prompt;taskCard.style.setProperty('--question-font',fonts[q.font]);taskCard.style.setProperty('--question-size',q.fontSize+'px');answers.style.fontFamily=fonts[q.font];
      if(q.image)media.append(img(q.image,'question-image','Question illustration'));
      if(q.audio){questionAudio=make('audio','question-audio');questionAudio.controls=true;questionAudio.preload='metadata';questionAudio.src=q.audio;questionAudio.muted=muted;questionAudio.setAttribute('aria-label','Question audio');media.append(questionAudio);}
      if(q.type==='choice'){
        const indices=q.options.map((_,i)=>i);for(let i=indices.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[indices[i],indices[j]]=[indices[j],indices[i]];}
        indices.forEach(i=>{const b=button(q.options[i],'',()=>answer(q.correctIndices.includes(i),b));b.dataset.option=i;answers.append(b);});
      }else{const form=make('form','text-answer'),input=make('input'),check=button(labels.check,'primary');input.type='text';input.autocomplete='off';input.placeholder=labels.placeholder;input.setAttribute('aria-label',labels.placeholder);check.type='submit';form.append(input,check);answers.append(form);form.onsubmit=e=>{e.preventDefault();answer(q.accepts.some(x=>x.trim().toLowerCase()===input.value.trim().toLowerCase()),input);};}
      timerBadge.hidden=!q.seconds;clearTimer();deadline=q.seconds?Date.now()+q.seconds*1000:0;
      const tick=()=>{if(state!=='question')return;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));timerBadge.textContent='◷ '+remaining;timerBadge.classList.toggle('urgent',remaining<=5);if(remaining===0)answer(false,null,true);};if(q.seconds){tick();timer=setInterval(tick,100);}
      qtext.focus({preventScroll:true});
      if(s.useMath&&window.MathJax?.startup?.promise){const ticket=generation;window.MathJax.startup.promise.then(()=>{if(ticket===generation&&state==='question')return window.MathJax.typesetPromise([qtext,answers]);}).catch(()=>{});}
    }
    function answer(isCorrect,target,timeout=false){
      if(state!=='question')return;if(deadline&&Date.now()>=deadline){isCorrect=false;timeout=true;}setState('feedback');clearTimer();if(questionAudio)questionAudio.pause();answers.querySelectorAll('button,input').forEach(e=>e.disabled=true);index++;updateControls();if(target)target.classList.add(isCorrect?'correct':'wrong');feedback.textContent=timeout?labels.timeout:isCorrect?labels.correct:labels.wrong;
      if(isCorrect){correct++;sound('correct');confetti();later(()=>{taskLayer.hidden=true;scratch.hidden=true;setState('dispensing');selected.collected=true;selected.element.style.top='115%';col=1;positionClaw();claw.classList.remove('closed');later(()=>{tray.replaceChildren(selected.element);selected.element.disabled=false;setState('collect');message.textContent=labels.collect;selected.element.focus({preventScroll:true});},650);},1500);}
      else{wrong++;sound('wrong');later(()=>{taskLayer.hidden=true;scratch.hidden=true;setState('returning');restore(selected);col=1;positionClaw();claw.classList.remove('closed');later(nextAttempt,650);},1200);}
    }
    function collectToy(){if(state!=='collect'||!selected)return;setState('collecting');selected.element.disabled=true;sound('coin');const slot=collection.children[correct-1];slot.replaceChildren(img(project.toys[selected.id].src||toyArt[selected.id],'',toyNames[selected.id],toyArt[selected.id]));slot.classList.add('won');selected.element.remove();tray.replaceChildren(document.createTextNode(labels.tray));later(nextAttempt,500);}
    function nextAttempt(){if(index>=9)finish();else waiting();}
    function finish(){cleanup();setState('finished');updateControls();screen.hidden=false;screenCard.replaceChildren(make('div','screen-mark','✦'),make('h1','',labels.finish),make('p','',s.finishText));const stats=make('div','result-stats');stats.append(make('span','',labels.rightCount+': '+correct),make('span','missed',labels.wrongCount+': '+wrong));const count=make('p','',labels.collected+': '+correct+' / 9');count.id='finish-score';screenCard.append(count,stats,button(labels.again,'primary',resetGame));screenCard.querySelector('button').focus({preventScroll:true});}
    function confetti(){if(reduced)return;for(let i=0;i<24;i++){const piece=make('i','confetti-piece');piece.style.setProperty('--dx',(Math.random()-.5)*450+'px');piece.style.setProperty('--dy',(Math.random()*300-70)+'px');piece.style.setProperty('--c',['#d4aa55','#7ba592','#c391a1'][i%3]);root.append(piece);later(()=>piece.remove(),950);}}
    window.addEventListener('keydown',e=>{if(state!=='playing'||/INPUT|TEXTAREA|BUTTON/.test(e.target.tagName))return;if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key===' '){e.preventDefault();grabToy();}});
    taskLayer.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...taskCard.querySelectorAll('button,input,audio[controls]')].filter(n=>!n.disabled&&!n.hidden&&n.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===qtext)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
    window.addEventListener('pagehide',()=>{cleanup();audioContext?.close().catch(()=>{});});
    resetGame();
  };
})();
