document.getElementById('builder').addEventListener('load',async function(){
  const frame=this,doc=frame.contentDocument,w=frame.contentWindow,IP=w.InkyPaws,list=document.getElementById('results');let passed=0,failed=0;
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  function assert(c,m='Assertion failed'){if(!c)throw new Error(m);}
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.className='pass';li.textContent='PASS · '+name;passed++;}catch(e){li.className='fail';li.textContent='FAIL · '+name+': '+e.message;failed++;}list.append(li);}
  function input(field,value){field.value=value;field.dispatchEvent(new w.Event('input',{bubbles:true}));}
  function action(card,prefix){return [...card.querySelectorAll('.card-actions button')].find(b=>b.getAttribute('aria-label').startsWith(prefix));}
  await test('Initial editor has three question types and a playable preview',async()=>{await wait(600);assert(doc.querySelectorAll('.question-card').length===3);assert(doc.getElementById('preview-frame').srcdoc.includes('A sky full of questions'));assert(!doc.getElementById('download-game').disabled);});
  await test('Duplicate, move up/down, and delete preserve question content',async()=>{let first=doc.querySelector('.question-card');action(first,'Duplicate').click();assert(doc.querySelectorAll('.question-card').length===4);let cards=doc.querySelectorAll('.question-card');assert(cards[0].querySelector('textarea').value===cards[1].querySelector('textarea').value);const id=cards[1].id;action(cards[1],'Move question 2 down').click();assert(doc.querySelectorAll('.question-card')[2].id===id);action(doc.getElementById(id),'Move question 3 up').click();assert(doc.querySelectorAll('.question-card')[1].id===id);action(doc.getElementById(id),'Delete').click();assert(doc.querySelectorAll('.question-card').length===3);});
  await test('Adding an incomplete question disables exports and preserves preview',async()=>{const html=doc.getElementById('preview-frame').srcdoc;doc.getElementById('add-question').click();await wait(600);assert(doc.getElementById('download-game').disabled);assert(!doc.getElementById('validation').hidden);assert(doc.getElementById('preview-frame').srcdoc===html);});
  await test('Question card can change type and become exportable',async()=>{const card=doc.querySelectorAll('.question-card')[3],select=card.querySelector('select');select.value='input';select.dispatchEvent(new w.Event('change',{bubbles:true}));const updated=doc.querySelectorAll('.question-card')[3];input(updated.querySelector('textarea'),'What is 2 + 2?');input(updated.querySelector('.correct-field input'),'4');await wait(600);assert(!doc.getElementById('download-game').disabled);assert(doc.getElementById('preview-frame').srcdoc.includes('What is 2 + 2?'));});
  await test('Settings and image upload are present in downloaded HTML and JSON',async()=>{doc.querySelector('[data-tab="settings"]').click();input(doc.getElementById('setting-title'),'My "original" & quiz');doc.querySelector('[data-tab="assets"]').click();const upload=doc.querySelector('#asset-fields input[type=file]');const png=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9x8AAAAASUVORK5CYII='),c=>c.charCodeAt(0));const dt=new w.DataTransfer();dt.items.add(new w.File([png],'image.png',{type:'image/png'}));upload.files=dt.files;upload.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(650);const blobs=[],names=[];const originalURL=w.URL.createObjectURL,originalClick=w.HTMLAnchorElement.prototype.click;w.URL.createObjectURL=blob=>{blobs.push(blob);return originalURL.call(w.URL,blob);};w.HTMLAnchorElement.prototype.click=function(){names.push(this.download);};doc.getElementById('save-project').click();doc.getElementById('download-game').click();await wait(80);w.URL.createObjectURL=originalURL;w.HTMLAnchorElement.prototype.click=originalClick;assert(blobs.length===2,'Expected JSON and HTML downloads, got '+blobs.length);const downloads=await Promise.all(blobs.map(async(blob,i)=>({text:await blob.text(),name:names[i]})));const p=JSON.parse(downloads[0].text);assert(p.questions.length===4);assert(p.assets.background.startsWith('data:image/png'));assert(p.settings.title==='My "original" & quiz');assert(downloads[1].text.includes(p.assets.background));assert(downloads[1].name.endsWith('.html'));window.savedProject=p;});
  await test('Load project restores cards and media',async()=>{const dt=new w.DataTransfer();const p=window.savedProject;p.questions=p.questions.slice(0,2);dt.items.add(new w.File([JSON.stringify(p)],'restored.json',{type:'application/json'}));const file=doc.getElementById('project-file');file.files=dt.files;file.dispatchEvent(new w.Event('change',{bubbles:true}));await wait(650);assert(doc.querySelectorAll('.question-card').length===2);assert(doc.getElementById('setting-title').value===p.settings.title);assert(doc.querySelector('#asset-fields .asset-preview').textContent.includes('Embedded'));});
  await test('Iframe copy uses current playable HTML',async()=>{let code;const orig=IP.Export.copy;IP.Export.copy=async t=>code=t;doc.getElementById('copy-embed').click();await wait(50);IP.Export.copy=orig;assert(code.startsWith('<iframe'));assert(code.includes('srcdoc='));assert(code.includes('sandbox="allow-scripts"'));});
  await test('Phone preview and mobile editor fit their viewport',async()=>{const size=doc.getElementById('preview-size');size.value='phone';size.dispatchEvent(new w.Event('change'));assert(doc.getElementById('preview-shell').classList.contains('phone'));frame.style.width='390px';await wait(200);assert(doc.documentElement.scrollWidth<=frame.clientWidth+1,'Builder overflows horizontally');});
  doc.querySelector('[data-tab="questions"]').click();document.getElementById('summary').textContent=passed+' passed, '+failed+' failed';document.body.dataset.result=failed?'fail':'pass';
});
