(async function(){
  const IP=window.InkyPaws, list=document.getElementById('results');let passed=0,failed=0;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function assert(condition,message='Assertion failed'){if(!condition)throw new Error(message);}
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.className='pass';li.textContent='PASS · '+name;passed++;}catch(e){li.className='fail';li.textContent='FAIL · '+name+': '+e.message;failed++;}list.append(li);}
  async function rejects(fn){let did=false;try{await fn();}catch(_){did=true;}assert(did,'Expected rejection');}
  function project(){const p=IP.Project.create();p.settings.animations=false;p.settings.soundEffects=false;return p;}
  let frame, doc;
  async function game(p){if(frame)frame.remove();frame=document.createElement('iframe');frame.title='Test game';const loaded=new Promise(r=>frame.onload=r);frame.srcdoc=IP.generateGameHtml(p);document.getElementById('frames').append(frame);await loaded;doc=frame.contentDocument;return doc;}
  async function start(){doc.querySelector('.main-button').click();await sleep(240);}
  function choose(text){const b=[...doc.querySelectorAll('#answers button')].find(b=>b.textContent===text);assert(b,'Missing answer '+text);b.click();}
  await test('Default project is valid and JSON round-trips',()=>{const p=project();assert(!IP.Project.validate(p).length);assert(JSON.stringify(IP.Project.import(JSON.parse(JSON.stringify(p))))===JSON.stringify(p));});
  await test('Drafts remain loadable but incomplete games cannot export',async()=>{const p=project();p.questions=[IP.Project.newQuestion()];assert(IP.Project.import(p).questions.length===1);assert(IP.Project.validate(p).length>=3);await rejects(()=>IP.generateGameHtml(p));});
  await test('Wrong builder, unknown versions, invalid ranges and unsafe URLs are rejected',async()=>{for(const change of [p=>p.builderType='other',p=>p.schemaVersion=2,p=>p.settings.lives=-2,p=>p.assets.character='javascript:alert(1)',p=>p.assets.music='file:///private.mp3']){const p=project();change(p);await rejects(()=>IP.Project.import(p));}});
  await test('Duplicate answer choices are rejected after normalization',()=>{const p=project();p.questions[0].wrongs[0]='  HUGE ';assert(IP.Project.validate(p).some(e=>e.includes('different')));});
  await test('Embedded image upload survives project and export',async()=>{const data='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9x8AAAAASUVORK5CYII=';const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));const p=project();p.assets.character=await IP.Assets.read(new File([bytes],'test.png',{type:'image/png'}),'image',5);const loaded=await IP.ProjectIO.load(new File([JSON.stringify(p)],'project.json',{type:'application/json'}));assert(loaded.assets.character.startsWith('data:image/png;base64,'));assert(IP.generateGameHtml(loaded).includes(loaded.assets.character));});
  await test('Invalid JSON and SVG uploads are rejected',async()=>{await rejects(()=>IP.ProjectIO.load(new File(['{oops'],'bad.json')));await rejects(()=>IP.Assets.read(new File(['<svg/>'],'unsafe.svg',{type:'image/svg+xml'}),'image',5));});
  await test('Export embeds escaped content as text without external default dependencies',async()=>{const p=project(),text='Quotes " & <b>tag</b> </script><script>window.__injected=1</script>';p.settings.title=text;p.questions[0].text=text;const html=IP.generateGameHtml(p);assert(!/<script[^>]+src=|<link[^>]+href=/.test(html));await game(p);assert(!frame.contentWindow.__injected);assert(doc.querySelector('#screen h1').textContent===text);await start();assert(doc.getElementById('question-text').textContent===text);});
  await test('Selected font reaches game text',async()=>{const p=project();p.settings.font='mono';await game(p);assert(frame.contentWindow.getComputedStyle(doc.querySelector('#screen h1')).fontFamily.includes('Courier New'));});
  await test('Iframe embed preserves the complete generated HTML',()=>{const html=IP.generateGameHtml(project()),host=document.createElement('div');host.innerHTML=IP.Export.iframeCode(html);const f=host.querySelector('iframe');assert(f.getAttribute('srcdoc')===html);assert(f.getAttribute('sandbox')==='allow-scripts');});
  await test('Incorrect choice loses exactly one life and retries the same question',async()=>{const p=project();await game(p);await start();choose('Quiet');choose('Quiet');assert(doc.querySelector('.lives').getAttribute('aria-label')==='2 lives remaining');await sleep(650);assert(!doc.querySelector('.answer').disabled);assert(doc.getElementById('question-text').textContent===p.questions[0].text);});
  await test('Correct choice advances and awards one collectible',async()=>{choose('Huge');await sleep(520);assert(doc.getElementById('coin-counter').textContent.includes('1'));assert(doc.getElementById('question-text').textContent.includes('Birds'));});
  await test('Typed answer trims and ignores case; Enter/form submission advances',async()=>{const input=doc.querySelector('.typed input');input.value='  FLY  ';doc.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));await sleep(520);assert(doc.querySelector('.order'));assert(doc.getElementById('coin-counter').textContent.includes('2'));});
  await test('Repeated word tokens can be reordered, submitted, and win with final star',async()=>{const p=project();p.questions=[{...IP.Project.newQuestion('order'),text:'Repeat words',correct:'go go home'}];await game(p);await start();for(const word of ['go','home','go']){const b=[...doc.querySelectorAll('.word-pool button')].find(b=>b.textContent===word);b.click();}assert(doc.querySelectorAll('.word-zone button').length===3);doc.querySelector('.order .submit').click();await sleep(650);assert(doc.querySelectorAll('.word-pool button').length===3);assert(doc.querySelector('.lives').getAttribute('aria-label')==='2 lives remaining');for(const word of ['go','go','home']){[...doc.querySelectorAll('.word-pool button')].find(b=>b.textContent===word).click();}doc.querySelector('.order .submit').click();await sleep(520);assert(!doc.getElementById('screen').hidden);assert(doc.querySelector('.result-count').textContent==='1 / 1 stars collected');});
  await test('Restart during feedback clears pending rewards and transitions',async()=>{const p=project();await game(p);await start();choose('Huge');[...doc.querySelectorAll('.hud button')].find(b=>b.textContent==='Restart').click();await sleep(700);assert(doc.getElementById('coin-counter').textContent.includes('0'));assert(doc.getElementById('question-text').textContent===p.questions[0].text);assert(doc.querySelector('.lives').getAttribute('aria-label')==='3 lives remaining');});
  await test('Timer expiry uses a life, resets the attempt, and supports game over/restart',async()=>{const p=project();p.settings.useTimer=true;p.settings.timerSeconds=5;p.settings.lives=2;await game(p);await start();await sleep(5300);assert(doc.querySelector('.lives').getAttribute('aria-label')==='1 lives remaining');await sleep(600);assert(doc.getElementById('timer').textContent==='00:05');choose('Quiet');await sleep(850);assert(!doc.getElementById('screen').hidden);assert(doc.querySelector('#screen h1').textContent===p.settings.loseText);await start();assert(doc.querySelector('.lives').getAttribute('aria-label')==='2 lives remaining');});
  await test('Long text remains horizontally contained at phone width',async()=>{const p=project();p.questions[0].text='A very long question '.repeat(40);p.questions[0].correct='AnExtremelyLongUnbrokenAnswer'.repeat(6);await game(p);await start();assert(doc.documentElement.scrollWidth<=frame.clientWidth+1,'Game overflows horizontally');assert(doc.documentElement.scrollHeight>frame.clientHeight,'Long content should be scrollable');});
  if(frame)frame.remove();document.getElementById('summary').textContent=passed+' passed, '+failed+' failed';document.body.dataset.result=failed?'fail':'pass';
})();
