(async function(){
const S=InkySlot,wait=ms=>new Promise(r=>setTimeout(r,ms));let passed=0,failed=0,frame,doc;
function assert(v,m='Assertion failed'){if(!v)throw Error(m)}
async function test(name,fn){const li=document.createElement('li');try{await fn();passed++;li.className='pass';li.textContent='PASS '+name}catch(e){failed++;li.className='fail';li.textContent='FAIL '+name+': '+e.message}document.querySelector('#results').append(li)}
function throws(fn){let error=false;try{fn()}catch(_){error=true}assert(error,'Expected rejection')}
async function until(state){for(let i=0;i<150;i++){if(doc.querySelector('#slot-game').dataset.state===state)return;await wait(25)}throw Error('Expected '+state+', got '+doc.querySelector('#slot-game').dataset.state)}
async function load(p){frame?.remove();frame=document.createElement('iframe');document.querySelector('#frames').append(frame);await new Promise(r=>{frame.onload=r;frame.srcdoc=S.Export.gameHTML(p)});doc=frame.contentDocument;assert(doc.querySelector('#play'),'Runtime did not start')}
function click(id){doc.getElementById(id).click()}
async function grab(col=1){click('insert-coin');if(col===0)click('move-left');if(col===2)click('move-right');click('grab');await until('question')}
const p=S.Project.create();p.settings.animations=false;p.settings.sounds=false;p.questions=p.questions.map((q,i)=>({...q,prompt:'Question '+i,type:'choice',options:['Yes','No','Also yes'],correctIndices:[0,2],seconds:null}));
await test('Nine-question schema, JSON round trip and foreign project rejection',()=>{assert(S.Project.validate(S.Project.read(JSON.parse(JSON.stringify(p)))).length===0);const draft=structuredClone(p);draft.questions.pop();assert(S.Project.validate(draft).length>0);throws(()=>S.Project.read({builderType:'flying-quiz'}));});
await test('Bulk import accepts alternatives and multiple correct choices',()=>{const q=S.Project.parseImport('Pet? | cat / kitten\nColor? | *red | blue | *green');assert(q.length===2&&q[0].accepts.length===2&&q[1].correctIndices.length===2);throws(()=>S.Project.parseImport('Missing separator'));});
await test('Export escapes script-like teacher text and rejects unsafe media',()=>{const x=structuredClone(p);x.questions[0].prompt='</script><script>window.BAD=true</script>';assert(!S.Export.gameHTML(x).includes('<script>window.BAD'));x.questions[0].image='javascript:alert(1)';throws(()=>S.Project.read(x));});
await test('Hosted iframe targets game HTML and rejects editor/local URLs',()=>{const code=S.Export.iframeCode('https://example.com/repo/games/test.html');assert(code.includes('src="https://example.com/repo/games/test.html"')&&!code.includes('srcdoc'));for(const url of ['file:///x.html','http://localhost/a.html','https://example.com/builders/slot-machine/index.html'])throws(()=>S.Export.iframeCode(url));});
await test('Coin gates movement and grab; random toy still uses first authored question',async()=>{await load(p);click('play');assert(doc.querySelector('#grab').disabled);await grab();assert(doc.querySelector('#question-text').textContent==='Question 0');assert(doc.querySelectorAll('#answers button').length===3);});
await test('Wrong answer returns toy and advances question, requiring another coin',async()=>{doc.querySelector('[data-option="1"]').click();await until('waiting-coin');assert(doc.querySelectorAll('#glass .toy').length===9);assert(doc.querySelector('#slot-game').dataset.attempt==='1');await grab();assert(doc.querySelector('#question-text').textContent==='Question 1');});
await test('Any marked answer wins; tray click is required to continue',async()=>{doc.querySelector('[data-option="2"]').click();await until('collect');await wait(180);assert(doc.querySelector('#slot-game').dataset.state==='collect');assert(doc.querySelectorAll('.collection-slot.won').length===0);doc.querySelector('#prize-tray .toy').click();await until('waiting-coin');assert(doc.querySelectorAll('.collection-slot.won').length===1);});
await test('Reset during a grab cancels pending question transitions',async()=>{click('insert-coin');click('grab');click('reset-game');await wait(250);assert(doc.querySelector('#slot-game').dataset.state==='start');assert(doc.querySelectorAll('#glass .toy').length===9);assert(doc.querySelectorAll('.collection-slot.won').length===0);});
await test('Typed alternatives ignore outer whitespace and case; timeout consumes question',async()=>{const x=structuredClone(p);x.questions[0].type='text';x.questions[0].accepts=['cat','kitten'];x.questions[1].seconds=3;await load(x);click('play');await grab();doc.querySelector('.text-answer input').value=' KITTEN ';doc.querySelector('.text-answer').requestSubmit();await until('collect');doc.querySelector('#prize-tray .toy').click();await until('waiting-coin');await grab();await until('waiting-coin');assert(doc.querySelector('#slot-game').dataset.attempt==='2');});
await test('Scratch paper draws and clears locally',async()=>{await grab();[...doc.querySelectorAll('.task-header button')][0].click();const canvas=doc.querySelector('canvas'),ctx=canvas.getContext('2d');assert(!doc.querySelector('#scratchpad').hidden&&canvas.width>0);ctx.fillRect(1,1,20,20);[...doc.querySelectorAll('.scratch-tools button')].find(b=>b.textContent==='Clear').click();assert(ctx.getImageData(2,2,1,1).data[3]===0);});
await test('Nine wins, empty-column handling and final tray collection precede finish',async()=>{await load(p);click('play');for(let i=0;i<9;i++){if(i===3){click('insert-coin');click('move-left');click('grab');await until('empty-column');assert(doc.querySelector('#slot-game').dataset.attempt==='3');doc.querySelector('#game-message button').click();click('move-right');click('grab');await until('question')}else await grab(Math.floor(i/3));doc.querySelector('[data-option="0"]').click();await until('collect');assert(doc.querySelector('#screen').hidden,'Finished before tray collection');doc.querySelector('#prize-tray .toy').click();await until(i===8?'finished':'waiting-coin')}assert(doc.querySelector('#finish-score').textContent.includes('9 / 9'));assert(doc.querySelectorAll('.collection-slot.won').length===9);doc.querySelector('#screen button').click();await until('start');});
await test('Embedded image, audio and optional LaTeX render without editor assets',async()=>{const x=structuredClone(p);x.settings.useMath=true;x.questions[0].prompt='$\\frac{1}{2}$';x.questions[0].image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';x.questions[0].audio='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';await load(x);click('play');await grab();for(let i=0;i<60&&!doc.querySelector('mjx-container svg');i++)await wait(50);assert(doc.querySelector('mjx-container svg'),'Math did not render');assert(doc.querySelector('.question-image').naturalWidth===1);assert(doc.querySelector('audio').src.startsWith('data:audio/'));assert(!doc.querySelector('#question-cards'));assert(doc.documentElement.scrollWidth<=390,'Phone game overflows');});
document.querySelector('#summary').textContent=passed+' passed, '+failed+' failed';document.body.dataset.result=failed?'fail':'pass';})();