(async function(){
const frame=document.querySelector('#editor'),wait=ms=>new Promise(r=>setTimeout(r,ms));let passed=0,failed=0;
await new Promise(r=>frame.addEventListener('load',r,{once:true}));const w=frame.contentWindow,d=frame.contentDocument,S=w.InkySlot;w.confirm=()=>true;let saved=null;S.Export.download=(text,type,name)=>{saved={text,type,name}};
const assert=(v,m='Assertion failed')=>{if(!v)throw Error(m)};
async function test(name,fn){const li=document.createElement('li');try{await fn();passed++;li.className='pass';li.textContent='PASS '+name}catch(e){failed++;li.className='fail';li.textContent='FAIL '+name+': '+e.message}document.querySelector('#results').append(li)}
const click=id=>d.getElementById(id).click();const action=(el,text)=>[...el.querySelectorAll('button')].find(b=>b.textContent===text).click();
function input(el,value){el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}))}
function upload(el,file){const dt=new w.DataTransfer();dt.items.add(file);el.files=dt.files;el.dispatchEvent(new w.Event('change',{bubbles:true}))}
await test('Initial editor has nine cards, preview and independent assets',()=>{assert(d.querySelectorAll('.question-card').length===9);assert(d.querySelector('#preview-frame').srcdoc.includes('slot-game'));assert(d.querySelector('#add-question').disabled);assert(d.querySelector('link').sheet.cssRules.length>0)});
await test('Delete, duplicate and reorder keep question data; drafts block export',async()=>{action(d.querySelector('.question-card'),'Delete');await wait(550);assert(d.querySelector('#download-game').disabled);action(d.querySelector('.question-card'),'Duplicate');assert(d.querySelectorAll('.question-card').length===9);action(d.querySelector('.question-card'),'↓');await wait(550);assert(!d.querySelector('#download-game').disabled)});
await test('Image and audio uploads survive project JSON and HTML export',async()=>{const extras=d.querySelector('.question-extras');extras.open=true;const files=extras.querySelectorAll('input[type=file]');assert(files.length===2);const png=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='),c=>c.charCodeAt(0));upload(files[0],new w.File([png],'pixel.png',{type:'image/png'}));upload(files[1],new w.File(['RIFF'],'sound.wav',{type:'audio/wav'}));await wait(750);click('save-project');assert(saved.type==='application/json');const p=JSON.parse(saved.text);assert(p.questions[0].image.startsWith('data:image/png'));assert(p.questions[0].audio.startsWith('data:audio/wav'));click('download-game');assert(saved.name.endsWith('.game.html'));assert(saved.text.includes(p.questions[0].image)&&saved.text.includes(p.questions[0].audio));});
await test('Load restores JSON, settings and media',async()=>{const p=S.Project.create();p.settings.title='Restored cabinet';p.toys[0].scale=1.4;upload(d.querySelector('#project-file'),new w.File([JSON.stringify(p)],'project.json',{type:'application/json'}));await wait(650);assert(d.querySelector('#setting-title').value==='Restored cabinet');click('save-project');assert(JSON.parse(saved.text).toys[0].scale===1.4)});
await test('Toy customization and settings reach the generated game',async()=>{d.querySelector('[data-tab=toys]').click();const slider=d.querySelector('#toy-editor input[type=range]');input(slider,'120');d.querySelector('[data-tab=settings]').click();input(d.querySelector('#setting-title'),'Custom cabinet');await wait(550);click('download-game');assert(saved.text.includes('Custom cabinet'));const parsed=new DOMParser().parseFromString(saved.text,'text/html');assert(JSON.parse(parsed.querySelector('#game-data').textContent).project.toys[0].scale===1.2)});
await test('Hosted iframe copies a finished game URL, without editor or srcdoc',async()=>{let copied='';S.Export.copy=async text=>{copied=text};input(d.querySelector('#hosted-url'),'https://example.com/repo/games/cabinet.html');click('copy-iframe');await wait(20);assert(copied.includes('src="https://example.com/repo/games/cabinet.html"'));assert(!copied.includes('srcdoc'));assert(d.querySelector('#embed-code').value===copied)});
await test('Bulk import rebuilds nine tasks and keeps answer formats',async()=>{d.querySelector('[data-tab=questions]').click();click('clear-questions');click('import-questions');input(d.querySelector('#import-text'),Array.from({length:9},(_,i)=>'Task '+i+' | yes / yeah').join('\n'));click('confirm-import');await wait(550);assert(d.querySelectorAll('.question-card').length===9);assert(!d.querySelector('#download-game').disabled);click('save-project');assert(JSON.parse(saved.text).questions.every(q=>q.type==='text'&&q.accepts.length===2))});
await test('Phone editor fits viewport',async()=>{frame.style.width='390px';await wait(100);assert(d.documentElement.scrollWidth<=390,'Editor overflows to '+d.documentElement.scrollWidth)});
document.querySelector('#summary').textContent=passed+' passed, '+failed+' failed';document.body.dataset.result=failed?'fail':'pass';})();
